/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeatherIndexRouteImport } from './routes/weather/index'
import { Route as WeatherCityRouteImport } from './routes/weather/$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherIndexRoute = WeatherIndexRouteImport.update({
  id: '/weather/',
  path: '/weather/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherCityRoute = WeatherCityRouteImport.update({
  id: '/weather/$city',
  path: '/weather/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/weather/$city': typeof WeatherCityRoute
  '/weather/': typeof WeatherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/weather/$city': typeof WeatherCityRoute
  '/weather': typeof WeatherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/weather/$city': typeof WeatherCityRoute
  '/weather/': typeof WeatherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/weather/$city' | '/weather/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/weather/$city' | '/weather'
  id: '__root__' | '/' | '/weather/$city' | '/weather/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WeatherCityRoute: typeof WeatherCityRoute
  WeatherIndexRoute: typeof WeatherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/': {
      id: '/weather/'
      path: '/weather'
      fullPath: '/weather/'
      preLoaderRoute: typeof WeatherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/$city': {
      id: '/weather/$city'
      path: '/weather/$city'
      fullPath: '/weather/$city'
      preLoaderRoute: typeof WeatherCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WeatherCityRoute: WeatherCityRoute,
  WeatherIndexRoute: WeatherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
