/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForecastIndexRouteImport } from './routes/forecast/index'
import { Route as ForecastCityRouteImport } from './routes/forecast/$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastIndexRoute = ForecastIndexRouteImport.update({
  id: '/forecast/',
  path: '/forecast/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastCityRoute = ForecastCityRouteImport.update({
  id: '/forecast/$city',
  path: '/forecast/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecast/$city': typeof ForecastCityRoute
  '/forecast/': typeof ForecastIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecast/$city': typeof ForecastCityRoute
  '/forecast': typeof ForecastIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecast/$city': typeof ForecastCityRoute
  '/forecast/': typeof ForecastIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forecast/$city' | '/forecast/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forecast/$city' | '/forecast'
  id: '__root__' | '/' | '/forecast/$city' | '/forecast/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecastCityRoute: typeof ForecastCityRoute
  ForecastIndexRoute: typeof ForecastIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast/': {
      id: '/forecast/'
      path: '/forecast'
      fullPath: '/forecast/'
      preLoaderRoute: typeof ForecastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast/$city': {
      id: '/forecast/$city'
      path: '/forecast/$city'
      fullPath: '/forecast/$city'
      preLoaderRoute: typeof ForecastCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecastCityRoute: ForecastCityRoute,
  ForecastIndexRoute: ForecastIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
